<a href="https://colab.research.google.com/github/thomsonmukungu/0xvip3r/blob/main/voterRegistration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.multioutput import MultiOutputRegressor

# loadung and processing the datasets
facebook_data = pd.read_csv('/content/facebook_data.csv')
facebook_data = facebook_data.dropna()
facebook_data = facebook_data.drop_duplicates()
instagram_data = pd.read_csv('/content/instagram_data.csv', encoding='latin1')
instagram_data =instagram_data.dropna()
twitter_data = pd.read_csv('/content/twitter_data.csv')
twitter_data = twitter_data.dropna()
voter_data = pd.read_csv('/content/voter_registration_data (1).csv')



In [17]:
data = pd.merge(facebook_data, instagram_data, on='voter_id')
data = pd.merge(data, twitter_data, on='voter_id')
data = pd.merge(data, voter_data, on='voter_id')

print('shape of the dataset: ', data.shape)
data.head(5)

shape of the dataset:  (100, 24)


user_id_x post_text  likes_x  shares  comments_x  support_candidate_a_x  \
0    user_0    post_0      536     356         181                      1   
1    user_1    post_1      103     358         197                      0   
2    user_2    post_2      217      59         134                      0   
3    user_3    post_3      539     140          22                      0   
4    user_4    post_4      134     187          44                      1   

   support_candidate_b_x  voter_id user_id_y photo_caption  ...  user_id  \
0                      1         1    user_0     caption_0  ...   user_0   
1                      1         2    user_1     caption_1  ...   user_1   
2                      1         3    user_2     caption_2  ...   user_2   
3                      1         4    user_3     caption_3  ...   user_3   
4                      0         5    user_4     caption_4  ...   user_4   

   tweet_text  retweets  favorites support_candidate_a support_candidate_b  \
0     tweet_0        47        598                   1                   1   
1     tweet_1       355        740                   0                   1   
2     tweet_2       150        299                   0                   1   
3     tweet_3       232        777                   1                   1   
4     tweet_4        20        324                   1                   1   

            name  age        address  party_affiliation  
0       John Doe   18    123 Main St         Democratic  
1     Jane Smith   62    456 Oak Ave         Democratic  
2    Bob Johnson   73  789 Pine Blvd        Independent  
3    Alice Brown   73     321 Elm Ln        Independent  
4  Charlie Davis   24   987 Cedar Rd         Democratic  

[5 rows x 24 columns]

In [20]:
from sklearn.model_selection import train_test_split


features = ['retweets', 'shares', 'likes_x']
targets = ['support_candidate_a_x', 'support_candidate_b_x', 'support_candidate_a', 'support_candidate_b']


X = data[features]
y = data[targets]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
rf_classifier_shares = RandomForestClassifier(n_estimators=100, random_state=42)

# Training the model
rf_classifier_shares.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [23]:
y_pred = rf_classifier_shares.predict(X_test)

print(y_pred)

[[1 1 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [1 0 1 0]
 [0 1 1 1]
 [1 1 1 0]
 [0 1 1 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [0 0 1 1]
 [0 1 1 0]
 [0 1 0 0]
 [0 1 1 1]
 [0 1 1 1]]


In [28]:
import joblib

# Assuming rf_classifier_shares is your trained RandomForestClassifier
rf_classifier_shares = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier_shares.fit(X_train, y_train)

# Save the model to a file
joblib.dump(rf_classifier_shares, 'rf_model_shares.joblib')

['rf_model_shares.joblib']

In [30]:
import joblib

# Load the saved model from the file
loaded_model = joblib.load('rf_model_shares.joblib')

new_data = X_test.iloc[0, :].values.reshape(1, -1)

# Make predictions using the loaded model
predictions = loaded_model.predict(new_data)

print("Predictions:", predictions)

Predictions: [[1 1 1 1]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
